# Generated by Django 3.2.3 on 2021-06-05 21:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_code', models.CharField(blank=True, help_text='Ref: https://api.paystack.co/bank', max_length=3, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('paystack_response', models.TextField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
